// openingBook.ts
//
// Lookup table for the first ~MAX_PLY plies.
// Entries are generated offline by scripts/buildOpeningBook.ts.
// The lookup is O(1) — Map<hash, {from,to}>.
//
// To regenerate:
//   npx tsx --tsconfig tsconfig.test.json scripts/buildOpeningBook.ts
// then paste the printed BOOK array below.

import { Move, generateMoves } from '../movegen';
import { Position } from '../position';
import { hashPosition } from './zobrist';

// [hash, from, to]  — generated by buildOpeningBook.ts
// Seed entries (8 moves from engine self-play); re-run the script for full coverage.
const BOOK: [number, number, number][] = [
  [2120013542, 26, 22],
  [2943209601,  6,  9],
  [3504885778, 31, 26],
  [3658850790,  2,  6],
  [2265423568, 22, 17],
  [1383768184,  9, 13],
  [1925486754, 17,  8],
  [ 205381744,  5, 12],
];

// O(1) lookup built once on module load
const BOOK_MAP = new Map<number, { from: number; to: number }>(
  BOOK.map(([hash, from, to]) => [hash, { from, to }]),
);

export function lookupOpeningBook(pos: Position): { move: Move } | undefined {
  const entry = BOOK_MAP.get(hashPosition(pos));
  if (!entry) return undefined;

  const move = generateMoves(pos).find(
    m => m.from === entry.from && m.to === entry.to,
  );
  if (!move) return undefined;
  return { move };
}
