// src/coreClaude/nnEval.ts
// Neural network evaluation — 128 → 256 → 128 → 1 (ReLU, linear output)
// Weights loaded from nnWeights.ts (generated by Colab + importNNWeights.ts)

import { bits }                              from './bitboards';
import { Position }                          from './position';
import { NN_W1, NN_b1, NN_W2, NN_b2, NN_W3, NN_b3, NN_ARCH } from './nnWeights';

const [IN, H1, H2] = NN_ARCH; // 128, 256, 128

// Pre-allocated buffers — avoids GC during search (eval called ~200k×/move)
const _x  = new Float32Array(IN);
const _h1 = new Float32Array(H1);
const _h2 = new Float32Array(H2);

export function nnEvaluate(p: Position): number {
  const side = p.side;

  // ── Build 128-dim one-hot feature vector (side-relative) ────────────────────
  _x.fill(0);
  for (const sq of bits(side === 1 ? p.p1Men   : p.p2Men))   _x[sq]      = 1;
  for (const sq of bits(side === 1 ? p.p1Kings : p.p2Kings)) _x[32 + sq] = 1;
  for (const sq of bits(side === 1 ? p.p2Men   : p.p1Men))   _x[64 + sq] = 1;
  for (const sq of bits(side === 1 ? p.p2Kings : p.p1Kings)) _x[96 + sq] = 1;

  // ── Layer 1: 128 → 256, ReLU ────────────────────────────────────────────────
  for (let i = 0; i < H1; i++) {
    let s = NN_b1[i];
    const row = i * IN;
    for (let j = 0; j < IN; j++) s += NN_W1[row + j] * _x[j];
    _h1[i] = s > 0 ? s : 0;
  }

  // ── Layer 2: 256 → 128, ReLU ────────────────────────────────────────────────
  for (let i = 0; i < H2; i++) {
    let s = NN_b2[i];
    const row = i * H1;
    for (let j = 0; j < H1; j++) s += NN_W2[row + j] * _h1[j];
    _h2[i] = s > 0 ? s : 0;
  }

  // ── Layer 3: 128 → 1, linear ────────────────────────────────────────────────
  let y = NN_b3[0];
  for (let j = 0; j < H2; j++) y += NN_W3[j] * _h2[j];

  return y | 0;
}
