// src/coreClaude/nnEval.ts
// Neural network evaluation — replaces hand-crafted eval after training.
//
// Architecture: 32 → 24 (ReLU) → 1 (linear)
// Weights are loaded from nnWeights.ts (generated by scripts/trainNN.ts).

import { bits } from './bitboards';
import { Position } from './position';
import { NN_W1, NN_b1, NN_W2, NN_b2 } from './nnWeights';

const H  = 24; // hidden size
const IN = 32; // input size

// Pre-allocated buffers — avoids GC pressure during search (eval called ~200k×/move)
const _x = new Float32Array(IN);
const _h = new Float32Array(H);

export function nnEvaluate(p: Position): number {
  const side = p.side;

  // ── Build feature vector (side-relative) ────────────────────────────────────
  _x.fill(0);
  for (const sq of bits(side === 1 ? p.p1Men   : p.p2Men))   _x[sq] =  1;
  for (const sq of bits(side === 1 ? p.p1Kings : p.p2Kings)) _x[sq] =  3;
  for (const sq of bits(side === 1 ? p.p2Men   : p.p1Men))   _x[sq] = -1;
  for (const sq of bits(side === 1 ? p.p2Kings : p.p1Kings)) _x[sq] = -3;

  // ── Layer 1: 32 → 24, ReLU ──────────────────────────────────────────────────
  for (let i = 0; i < H; i++) {
    let s = NN_b1[i];
    const row = i * IN;
    for (let j = 0; j < IN; j++) s += NN_W1[row + j] * _x[j];
    _h[i] = s > 0 ? s : 0;
  }

  // ── Output layer: 24 → 1, linear ────────────────────────────────────────────
  let y = NN_b2[0];
  for (let j = 0; j < H; j++) y += NN_W2[j] * _h[j];

  return y | 0; // truncate to integer centipawns
}
