// src/coreClaude/nnWeights.ts
// Auto-generated by scripts/importNNWeights.ts after Colab training.
// Run: npx tsx --tsconfig tsconfig.test.json scripts/importNNWeights.ts
//
// Architecture: 128 → 256 → 128 → 1
// Input: 4-channel one-hot (my_men[32], my_kings[32], enemy_men[32], enemy_kings[32])

export const NN_TRAINED = false; // set to true after importNNWeights.ts
export const NN_ARCH    = [128, 256, 128, 1] as const;

// Placeholder zeros — engine falls back to hand-crafted eval when NN_TRAINED=false
export const NN_W1 = new Float32Array(256 * 128);
export const NN_b1 = new Float32Array(256);
export const NN_W2 = new Float32Array(128 * 256);
export const NN_b2 = new Float32Array(128);
export const NN_W3 = new Float32Array(128);
export const NN_b3 = new Float32Array(1);
