// scripts/importNNWeights.ts
//
// Convert nn_weights.json (from Colab) → src/coreClaude/nnWeights.ts
//
// Usage:
//   npx tsx --tsconfig tsconfig.test.json scripts/importNNWeights.ts

import * as fs from 'fs';
import * as path from 'path';

const JSON_PATH = path.join(process.cwd(), 'data', 'nn_weights.json');
const OUT_PATH  = path.join(process.cwd(), 'src', 'coreClaude', 'nnWeights.ts');

if (!fs.existsSync(JSON_PATH)) {
  console.error(`Not found: ${JSON_PATH}`);
  console.error('Download nn_weights.json from Google Drive and put it in data/');
  process.exit(1);
}

const w = JSON.parse(fs.readFileSync(JSON_PATH, 'utf8'));
const [IN, H1, H2] = [w.arch[0], w.arch[1], w.arch[2]]; // 128, 256, 128

function fmt(arr: number[][]|number[]): string {
  const flat = Array.isArray(arr[0]) ? (arr as number[][]).flat() : arr as number[];
  return flat.map((v: number) => v.toFixed(6)).join(',');
}

const ts = `// src/coreClaude/nnWeights.ts
// Auto-generated by scripts/importNNWeights.ts
// Source: Colab training  |  Val RMSE: ${w.rmse} cp
// Architecture: ${w.arch.join(' → ')}

export const NN_TRAINED = true;
export const NN_ARCH    = ${JSON.stringify(w.arch)} as const; // [IN, H1, H2, OUT]

// Layer 1: ${IN} → ${H1}
export const NN_W1 = new Float32Array([${fmt(w.W1)}]);
export const NN_b1 = new Float32Array([${fmt(w.b1)}]);

// Layer 2: ${H1} → ${H2}
export const NN_W2 = new Float32Array([${fmt(w.W2)}]);
export const NN_b2 = new Float32Array([${fmt(w.b2)}]);

// Layer 3: ${H2} → 1
export const NN_W3 = new Float32Array([${fmt(w.W3)}]);
export const NN_b3 = new Float32Array([${fmt(w.b3)}]);
`;

fs.writeFileSync(OUT_PATH, ts);
console.log(`Written to ${OUT_PATH}`);
console.log(`Architecture: ${w.arch.join(' → ')}  |  Val RMSE: ${w.rmse} cp`);
console.log(`\nNext: run matchup to verify improvement`);
console.log(`  npx tsx --tsconfig tsconfig.test.json scripts/evalAB.ts`);
