import { strict as assert } from 'node:assert';
import { readFileSync } from 'node:fs';
import { DEFAULT_ASPIRATION_PROFILE, DEFAULT_EXTENSION_FEATURES, DEFAULT_LMR_PROFILE, DEFAULT_MOVE_ORDERING_FEATURES, DEFAULT_PRUNING_PROFILE, DEFAULT_SEARCH_FEATURES, fixedNodeSearch, SearchResult } from '../src/coreClaude/search/alphabeta';
import { generateMoves } from '../src/coreClaude/movegen';
import { TT } from '../src/coreClaude/search/tt';
import { hashPosition } from '../src/coreClaude/search/zobrist';
import { makePhase3hEnginePair } from './phase3hAspirationRunner';
import { SEARCH_ABLATION_START_SUITE, EXTENSION_CONFIRMATION_START_SUITE, PHASE3C_CONFIRMATION_START_SUITE, PHASE3C_FINAL_CONFIRMATION_START_SUITE, PHASE3D_CONFIRMATION_START_SUITE, PHASE3E_MOVE_ORDERING_START_SUITE, PHASE3F_LMR_START_SUITE, PHASE3G_PRUNING_START_SUITE, PHASE3H_ASPIRATION_SEED, PHASE3H_ASPIRATION_START_SUITE, PHASE3H_ASPIRATION_V1_FINGERPRINT, searchAblationSuiteFingerprint } from './tournamentStartSuite';
const config=JSON.parse(readFileSync('config/phase3h-aspiration-v1.json','utf8'));
assert.equal(DEFAULT_ASPIRATION_PROFILE,'current');assert.equal(DEFAULT_PRUNING_PROFILE,'current');assert.equal(DEFAULT_LMR_PROFILE,'current');assert.equal(PHASE3H_ASPIRATION_SEED,695272925);assert.equal(PHASE3H_ASPIRATION_START_SUITE.starts.length,64);assert.equal(PHASE3H_ASPIRATION_V1_FINGERPRINT,'18c227cee03578f11f4b9ecfa86899bbbc00344abe8c84aff2832551bead0098');assert.equal(searchAblationSuiteFingerprint(PHASE3H_ASPIRATION_START_SUITE),config.fingerprint);
const key=(p:typeof PHASE3H_ASPIRATION_START_SUITE.starts[number]['position'])=>[p.side,p.p1Men>>>0,p.p1Kings>>>0,p.p2Men>>>0,p.p2Kings>>>0,p.halfmoveClock].join(':');
const prior=new Set([...SEARCH_ABLATION_START_SUITE.starts,...EXTENSION_CONFIRMATION_START_SUITE.starts,...PHASE3C_CONFIRMATION_START_SUITE.starts,...PHASE3C_FINAL_CONFIRMATION_START_SUITE.starts,...PHASE3D_CONFIRMATION_START_SUITE.starts,...PHASE3E_MOVE_ORDERING_START_SUITE.starts,...PHASE3F_LMR_START_SUITE.starts,...PHASE3G_PRUNING_START_SUITE.starts].map(s=>key(s.position)));
assert.equal(new Set(PHASE3H_ASPIRATION_START_SUITE.starts.map(s=>key(s.position))).size,64);assert(PHASE3H_ASPIRATION_START_SUITE.starts.every(s=>!prior.has(key(s.position))));assert.deepEqual(config.baselineSearch,DEFAULT_SEARCH_FEATURES);assert.deepEqual(config.baselineExtensions,DEFAULT_EXTENSION_FEATURES);assert.deepEqual(config.baselineMoveOrdering,DEFAULT_MOVE_ORDERING_FEATURES);
const signature=(r:SearchResult)=>({best:r.best,score:r.score,depth:r.depth,pv:r.pv,nodes:r.nodes,qnodes:r.qnodes});
async function identity(p:typeof PHASE3H_ASPIRATION_START_SUITE.starts[number]['position']){const h=[hashPosition(p)];const a=await fixedNodeSearch(p,5000,new TT(),h);const b=await fixedNodeSearch(p,5000,new TT(),h,64,undefined,{}, {}, {},{lmrProfile:'current',pruningProfile:'current',aspirationProfile:'current'});const c=await fixedNodeSearch(p,5000,new TT(),h,64,undefined,{}, {}, {},{lmrProfile:'current',pruningProfile:'current',aspirationProfile:'current',collectAspirationStats:true});assert.equal(a.aspirationStats,undefined);assert.equal(b.aspirationStats,undefined);assert(c.aspirationStats);assert.deepEqual(signature(a),signature(b));assert.deepEqual(signature(a),signature(c));}
async function main(){const quiet=PHASE3H_ASPIRATION_START_SUITE.starts.find(s=>generateMoves(s.position)[0]?.captured.length===0)!.position;const capture=PHASE3H_ASPIRATION_START_SUITE.starts.find(s=>generateMoves(s.position)[0]?.captured.length)! .position;await identity(quiet);await identity(capture);for(const profile of config.inventory){const [baseline,candidate]=makePhase3hEnginePair(profile,{mode:'nodes',budget:5000,maxDepth:64});assert.deepEqual(baseline.measurementOptions,{lmrProfile:'current',pruningProfile:'current',aspirationProfile:'current',collectAspirationStats:true});assert.equal(candidate.measurementOptions?.aspirationProfile,profile);assert.equal(candidate.measurementOptions?.collectAspirationStats,true);}const [a,b]=makePhase3hEnginePair('off',{mode:'time',budget:100,maxDepth:64});assert.equal(a.measurementOptions?.collectAspirationStats,undefined);assert.equal(b.measurementOptions?.collectAspirationStats,undefined);
const before=await fixedNodeSearch(quiet,5000,new TT(),[hashPosition(quiet)]);const measured=await fixedNodeSearch(quiet,5000,new TT(),[hashPosition(quiet)],64,undefined,{}, {}, {},{aspirationProfile:'narrow-75',collectAspirationStats:true});assert(measured.aspirationStats);const after=await fixedNodeSearch(quiet,5000,new TT(),[hashPosition(quiet)]);assert.deepEqual(signature(after),signature(before));assert.equal(after.aspirationStats,undefined);
console.log('PASS Phase 3H frozen corpus/profiles, quiet/capture identity, instrumentation neutrality, equal-time instrumentation-off, and search-state isolation');}
main().catch(e=>{console.error(e);process.exitCode=1});
