import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { DEFAULT_EXTENSION_FEATURES, DEFAULT_MOVE_ORDERING_FEATURES, DEFAULT_SEARCH_FEATURES,
  ExtensionFeatureFlags, MoveOrderingFeatureFlags, SearchFeatureFlags } from '../src/coreClaude/search/alphabeta';
import { EloValue, EngineTotals, runTournament, saveTournament, SearchControl, TournamentResult } from './tournamentHarness';
import { PHASE3E_MOVE_ORDERING_START_SUITE, PHASE3E_MOVE_ORDERING_V1_FINGERPRINT } from './tournamentStartSuite';
const CONFIG='config/phase3e-move-ordering-v1.json';
type Candidate=keyof MoveOrderingFeatureFlags;
type Config={teacherIdentity:string;suite:string;seed:number;fingerprint:string;inventory:Candidate[];selectionRule:string;
 screening:{startOffset:number;pairedStarts:number;nodesPerMove:number;maxDepth:number;maxPlies:number};
 confirmation:{startOffset:number;pairedStarts:number;nodeBudgets:number[];timeBudgetsMs:number[];maxDepth:number;maxPlies:number};
 baselineSearch:SearchFeatureFlags;baselineExtensions:ExtensionFeatureFlags;baselineMoveOrdering:MoveOrderingFeatureFlags};
const config=JSON.parse(readFileSync(CONFIG,'utf8')) as Config;
const arg=(n:string)=>process.argv.find(x=>x.startsWith(`--${n}=`))?.slice(n.length+3);
const elo=(v:EloValue|null)=>v?.kind==='finite'?v.value:v?.kind??null;
const metrics=(x:EngineTotals)=>({averageDepth:x.averageDepth,nodes:x.nodes,qnodes:x.qnodes,elapsedMs:x.elapsedMs,nps:x.nps,moves:x.moves,moveOrderingStats:x.moveOrderingStats});
function concise(feature:Candidate,result:TournamentResult){return{featureDisabled:feature,wdl:{wins:result.summary.scoreEligibleCandidateWins,draws:result.summary.scoreEligibleDraws,losses:result.summary.scoreEligibleBaselineWins},scorePercent:result.summary.candidateScorePercent,elo:elo(result.summary.eloDifference),scoreCI95:result.summary.scoreConfidenceInterval95,eloCI95:result.summary.eloConfidenceInterval95.map(elo),baselineMetrics:metrics(result.engines.baseline),candidateMetrics:metrics(result.engines[`without-${feature}`]),unresolved:result.summary.unresolved,errors:result.summary.errors};}
function validate(){if(config.suite!==PHASE3E_MOVE_ORDERING_START_SUITE.version||config.seed!==PHASE3E_MOVE_ORDERING_START_SUITE.seed||config.fingerprint!==PHASE3E_MOVE_ORDERING_V1_FINGERPRINT)throw new Error('frozen Phase 3E corpus identity mismatch');if(JSON.stringify(config.baselineSearch)!==JSON.stringify(DEFAULT_SEARCH_FEATURES)||JSON.stringify(config.baselineExtensions)!==JSON.stringify(DEFAULT_EXTENSION_FEATURES)||JSON.stringify(config.baselineMoveOrdering)!==JSON.stringify(DEFAULT_MOVE_ORDERING_FEATURES))throw new Error('explicit Teacher v1 baseline no longer matches production semantics');}
async function run(feature:Candidate,control:SearchControl,offset:number,pairs:number,maxPlies:number,label:string,out:string){const candidateOrdering={...config.baselineMoveOrdering,[feature]:false};const baseline={id:'baseline',name:'Teacher v1 explicit baseline',search:control,featureOverrides:config.baselineSearch,extensionOverrides:config.baselineExtensions,moveOrderingOverrides:config.baselineMoveOrdering};const candidate={id:`without-${feature}`,name:`Teacher v1 without ${feature} ordering`,search:control,featureOverrides:config.baselineSearch,extensionOverrides:config.baselineExtensions,moveOrderingOverrides:candidateOrdering};const result=await runTournament(baseline,candidate,PHASE3E_MOVE_ORDERING_START_SUITE,{startOffset:offset,startLimit:pairs,maxPlies,allowDescriptiveStatistics:control.mode==='time'});saveTournament(result,`${out}/${label}`);return concise(feature,result);}
(async()=>{validate();const stage=arg('stage')??'screening',out=arg('output')??`.tmp/phase3e-${stage}`;mkdirSync(out,{recursive:true});const results=[];
 if(stage==='screening'){const s=config.screening;const requested=(arg('features')??config.inventory.join(',')).split(',') as Candidate[];if(requested.some(x=>!config.inventory.includes(x)))throw new Error('unknown --features candidate');for(const feature of requested){const x=await run(feature,{mode:'nodes',budget:s.nodesPerMove,maxDepth:s.maxDepth},s.startOffset,s.pairedStarts,s.maxPlies,feature,out);results.push(x);console.log(feature,x.wdl,x.scorePercent,x.eloCI95);}const favorable=results.filter(x=>(x.scorePercent??0)>50).sort((a,b)=>(b.scorePercent??0)-(a.scorePercent??0));const selected=favorable[0]?.featureDisabled??null;writeFileSync(`${out}/summary.json`,JSON.stringify({schemaVersion:'makhos-phase3e-screening-v1',config,selected,decision:selected?'confirm strongest point estimate':'inconclusive; stop',results},null,2)+'\n');console.log('selected',selected);
 }else if(stage==='confirmation'){const feature=arg('feature') as Candidate;if(!config.inventory.includes(feature))throw new Error('--feature must be the mechanically selected screening candidate');const c=config.confirmation;const requestedNodes=(arg('nodes')??c.nodeBudgets.join(',')).split(',').filter(Boolean).map(Number);const requestedTimes=(arg('times')??c.timeBudgetsMs.join(',')).split(',').filter(Boolean).map(Number);if(requestedNodes.some(n=>!c.nodeBudgets.includes(n))||requestedTimes.some(n=>!c.timeBudgetsMs.includes(n)))throw new Error('confirmation budgets must be frozen values');for(const n of requestedNodes)results.push(await run(feature,{mode:'nodes',budget:n,maxDepth:c.maxDepth},c.startOffset,c.pairedStarts,c.maxPlies,`nodes-${n}`,out));for(const ms of requestedTimes)results.push(await run(feature,{mode:'time',budget:ms,maxDepth:c.maxDepth},c.startOffset,c.pairedStarts,c.maxPlies,`time-${ms}ms`,out));writeFileSync(`${out}/summary.json`,JSON.stringify({schemaVersion:'makhos-phase3e-confirmation-v1',config,feature,results},null,2)+'\n');
 }else throw new Error('stage must be screening or confirmation');})().catch(e=>{console.error(e);process.exitCode=1});
