import { strict as assert } from 'node:assert';
import { readFileSync } from 'node:fs';
import { DEFAULT_EXTENSION_FEATURES, DEFAULT_LMR_PROFILE, DEFAULT_MOVE_ORDERING_FEATURES, DEFAULT_PRUNING_PROFILE, DEFAULT_SEARCH_FEATURES, fixedDepthScoreAtPlyForTesting, fixedNodeSearch, resetSearchHeuristicsForMeasurement, SearchResult } from '../src/coreClaude/search/alphabeta';
import { generateMoves } from '../src/coreClaude/movegen';
import { TT } from '../src/coreClaude/search/tt';
import { hashPosition } from '../src/coreClaude/search/zobrist';
import { makePhase3gEnginePair } from './phase3gPruningRunner';
import { SEARCH_ABLATION_START_SUITE, EXTENSION_CONFIRMATION_START_SUITE, PHASE3C_CONFIRMATION_START_SUITE, PHASE3C_FINAL_CONFIRMATION_START_SUITE, PHASE3D_CONFIRMATION_START_SUITE, PHASE3E_MOVE_ORDERING_START_SUITE, PHASE3F_LMR_START_SUITE, PHASE3G_PRUNING_SEED, PHASE3G_PRUNING_START_SUITE, PHASE3G_PRUNING_V1_FINGERPRINT, searchAblationSuiteFingerprint } from './tournamentStartSuite';
const config=JSON.parse(readFileSync('config/phase3g-pruning-v1.json','utf8'));
assert.equal(DEFAULT_PRUNING_PROFILE,'current');assert.equal(DEFAULT_LMR_PROFILE,'current');assert.equal(PHASE3G_PRUNING_SEED,4200662694);assert.equal(PHASE3G_PRUNING_START_SUITE.starts.length,64);assert.equal(PHASE3G_PRUNING_V1_FINGERPRINT,'8bc0ad868e0ffa58d8449dad8c5428f7dc7ddd81af2ecc497faeb31754844967');assert.equal(searchAblationSuiteFingerprint(PHASE3G_PRUNING_START_SUITE),config.fingerprint);
const key=(p:typeof PHASE3G_PRUNING_START_SUITE.starts[number]['position'])=>[p.side,p.p1Men>>>0,p.p1Kings>>>0,p.p2Men>>>0,p.p2Kings>>>0,p.halfmoveClock].join(':');
const prior=new Set([...SEARCH_ABLATION_START_SUITE.starts,...EXTENSION_CONFIRMATION_START_SUITE.starts,...PHASE3C_CONFIRMATION_START_SUITE.starts,...PHASE3C_FINAL_CONFIRMATION_START_SUITE.starts,...PHASE3D_CONFIRMATION_START_SUITE.starts,...PHASE3E_MOVE_ORDERING_START_SUITE.starts,...PHASE3F_LMR_START_SUITE.starts].map(s=>key(s.position)));
assert.equal(new Set(PHASE3G_PRUNING_START_SUITE.starts.map(s=>key(s.position))).size,64);assert(PHASE3G_PRUNING_START_SUITE.starts.every(s=>!prior.has(key(s.position))));assert.deepEqual(config.baselineSearch,DEFAULT_SEARCH_FEATURES);assert.deepEqual(config.baselineExtensions,DEFAULT_EXTENSION_FEATURES);assert.deepEqual(config.baselineMoveOrdering,DEFAULT_MOVE_ORDERING_FEATURES);
const signature=(r:SearchResult)=>({best:r.best,score:r.score,depth:r.depth,pv:r.pv,nodes:r.nodes,qnodes:r.qnodes});
async function identity(p:typeof PHASE3G_PRUNING_START_SUITE.starts[number]['position']){const h=[hashPosition(p)];const a=await fixedNodeSearch(p,5000,new TT(),h);const b=await fixedNodeSearch(p,5000,new TT(),h,64,undefined,{}, {}, {},{lmrProfile:'current',pruningProfile:'current'});const c=await fixedNodeSearch(p,5000,new TT(),h,64,undefined,{}, {}, {},{lmrProfile:'current',pruningProfile:'current',collectPruningStats:true});assert.equal(a.pruningStats,undefined);assert.equal(b.pruningStats,undefined);assert(c.pruningStats);assert.deepEqual(signature(a),signature(b));assert.deepEqual(signature(a),signature(c));}
async function main(){const quiet=PHASE3G_PRUNING_START_SUITE.starts.find(s=>generateMoves(s.position)[0]?.captured.length===0)!.position;const capture=PHASE3G_PRUNING_START_SUITE.starts.find(s=>generateMoves(s.position)[0]?.captured.length)! .position;await identity(quiet);await identity(capture);for(const profile of config.inventory){const [baseline,candidate]=makePhase3gEnginePair(profile,{mode:'nodes',budget:5000,maxDepth:64});assert.deepEqual(baseline.measurementOptions,{lmrProfile:'current',pruningProfile:'current',collectPruningStats:true});assert.equal(candidate.measurementOptions?.pruningProfile,profile);assert.equal(candidate.measurementOptions?.collectPruningStats,true);}const [a,b]=makePhase3gEnginePair('null-delayed',{mode:'time',budget:100,maxDepth:64});assert.equal(a.measurementOptions?.collectPruningStats,undefined);assert.equal(b.measurementOptions?.collectPruningStats,undefined);
resetSearchHeuristicsForMeasurement();const directDefault=fixedDepthScoreAtPlyForTesting(quiet,4,0,new TT());const measured=await fixedNodeSearch(quiet,5000,new TT(),[hashPosition(quiet)],64,undefined,{}, {}, {},{pruningProfile:'razoring-conservative',collectPruningStats:true});assert(measured.pruningStats);const statsSnapshot=structuredClone(measured.pruningStats);resetSearchHeuristicsForMeasurement();const directAfterMeasured=fixedDepthScoreAtPlyForTesting(quiet,4,0,new TT());assert.equal(directAfterMeasured,directDefault);assert.deepEqual(measured.pruningStats,statsSnapshot);
console.log('PASS Phase 3G frozen corpus/profiles, instrumentation, quiet/capture explicit-current identity, equal-time isolation, and direct-negamax state isolation');}
main().catch(e=>{console.error(e);process.exitCode=1});
