import { strict as assert } from 'node:assert';
import { B1 } from '../src/coreClaude/bitboards';
import { initialPosition, Position } from '../src/coreClaude/position';
import { DEFAULT_EXTENSION_FEATURES, fixedNodeSearch, moveKey } from '../src/coreClaude/search/alphabeta';
import { TT } from '../src/coreClaude/search/tt';
import { EXTENSION_CONFIRMATION_START_SUITE, EXTENSION_CONFIRMATION_V1_FINGERPRINT, PHASE3C_CONFIRMATION_START_SUITE, PHASE3C_CONFIRMATION_V1_FINGERPRINT, PHASE3C_FINAL_CONFIRMATION_START_SUITE, PHASE3C_FINAL_CONFIRMATION_V1_FINGERPRINT, SEARCH_ABLATION_START_SUITE, searchAblationSuiteFingerprint } from './tournamentStartSuite';
const sig=(r:Awaited<ReturnType<typeof fixedNodeSearch>>)=>JSON.stringify({best:r.best&&{from:r.best.from,to:r.best.to,captured:r.best.captured,path:r.best.path,promote:r.best.promote},score:r.score,depth:r.depth,pv:r.pv.map(moveKey)});
const allOff=Object.fromEntries(Object.keys(DEFAULT_EXTENSION_FEATURES).map(k=>[k,false]));
const positions:{name:string;pos:Position}[]=[
 {name:'ordinary quiet',pos:initialPosition()},
 {name:'forced capture',pos:{side:1,p1Men:B1(13)|B1(16),p1Kings:0,p2Men:B1(9)|B1(12),p2Kings:0,halfmoveClock:0}},
 {name:'multi capture',pos:{side:1,p1Men:B1(21),p1Kings:0,p2Men:B1(17)|B1(10),p2Kings:0,halfmoveClock:0}},
 {name:'small endgame',pos:{side:1,p1Men:B1(21)|B1(25),p1Kings:0,p2Men:B1(10)|B1(14),p2Kings:0,halfmoveClock:0}},
 {name:'low mobility root',pos:{side:1,p1Men:B1(21)|B1(24),p1Kings:0,p2Men:B1(9)|B1(13)|B1(17),p2Kings:0,halfmoveClock:0}},
];
(async()=>{for(const f of positions){const baseline=await fixedNodeSearch(f.pos,2000,new TT());const explicit=await fixedNodeSearch(f.pos,2000,new TT(),[],64,undefined,{},DEFAULT_EXTENSION_FEATURES);assert.equal(sig(explicit),sig(baseline),`${f.name}: enabled defaults changed semantics`);const master=await fixedNodeSearch(f.pos,2000,new TT(),[],64,undefined,{extensions:false});const subtypes=await fixedNodeSearch(f.pos,2000,new TT(),[],64,undefined,{},allOff);assert.equal(sig(subtypes),sig(master),`${f.name}: master-off differs from every subtype off`);assert.ok(baseline.extensionStats);}
 const oldStates=new Set(SEARCH_ABLATION_START_SUITE.starts.map(s=>JSON.stringify(s.position)));assert.equal(EXTENSION_CONFIRMATION_START_SUITE.starts.length,64);assert.equal(new Set(EXTENSION_CONFIRMATION_START_SUITE.starts.map(s=>JSON.stringify(s.position))).size,64);assert.ok(EXTENSION_CONFIRMATION_START_SUITE.starts.every(s=>!oldStates.has(JSON.stringify(s.position))));assert.equal(searchAblationSuiteFingerprint(EXTENSION_CONFIRMATION_START_SUITE),EXTENSION_CONFIRMATION_V1_FINGERPRINT);
 const priorStates=new Set([...SEARCH_ABLATION_START_SUITE.starts,...EXTENSION_CONFIRMATION_START_SUITE.starts].map(s=>JSON.stringify(s.position)));assert.equal(PHASE3C_CONFIRMATION_START_SUITE.starts.length,64);assert.equal(new Set(PHASE3C_CONFIRMATION_START_SUITE.starts.map(s=>JSON.stringify(s.position))).size,64);assert.ok(PHASE3C_CONFIRMATION_START_SUITE.starts.every(s=>!priorStates.has(JSON.stringify(s.position))));assert.equal(searchAblationSuiteFingerprint(PHASE3C_CONFIRMATION_START_SUITE),PHASE3C_CONFIRMATION_V1_FINGERPRINT);
 const allPriorStates=new Set([...SEARCH_ABLATION_START_SUITE.starts,...EXTENSION_CONFIRMATION_START_SUITE.starts,...PHASE3C_CONFIRMATION_START_SUITE.starts].map(s=>JSON.stringify(s.position)));assert.equal(PHASE3C_FINAL_CONFIRMATION_START_SUITE.starts.length,64);assert.equal(new Set(PHASE3C_FINAL_CONFIRMATION_START_SUITE.starts.map(s=>JSON.stringify(s.position))).size,64);assert.ok(PHASE3C_FINAL_CONFIRMATION_START_SUITE.starts.every(s=>!allPriorStates.has(JSON.stringify(s.position))));assert.equal(searchAblationSuiteFingerprint(PHASE3C_FINAL_CONFIRMATION_START_SUITE),PHASE3C_FINAL_CONFIRMATION_V1_FINGERPRINT);console.log('PASS extension semantic preservation, instrumentation, and frozen disjoint corpora');})();
