import { strict as assert } from 'node:assert';
import { readFileSync } from 'node:fs';
import { DEFAULT_LMR_PROFILE, DEFAULT_EXTENSION_FEATURES, DEFAULT_MOVE_ORDERING_FEATURES, DEFAULT_SEARCH_FEATURES, fixedDepthScoreAtPlyForTesting, fixedNodeSearch, resetSearchHeuristicsForMeasurement, SearchResult } from '../src/coreClaude/search/alphabeta';
import { TT } from '../src/coreClaude/search/tt';
import { hashPosition } from '../src/coreClaude/search/zobrist';
import { makePhase3fEnginePair } from './phase3fLmrRunner';
import { SEARCH_ABLATION_START_SUITE, EXTENSION_CONFIRMATION_START_SUITE, PHASE3C_CONFIRMATION_START_SUITE, PHASE3C_FINAL_CONFIRMATION_START_SUITE, PHASE3D_CONFIRMATION_START_SUITE, PHASE3E_MOVE_ORDERING_START_SUITE, PHASE3F_LMR_SEED, PHASE3F_LMR_START_SUITE, PHASE3F_LMR_V1_FINGERPRINT, searchAblationSuiteFingerprint } from './tournamentStartSuite';
const config=JSON.parse(readFileSync('config/phase3f-lmr-v1.json','utf8'));
assert.equal(DEFAULT_LMR_PROFILE,'current');assert.equal(PHASE3F_LMR_SEED,2181625590);assert.equal(PHASE3F_LMR_START_SUITE.starts.length,64);assert.equal(PHASE3F_LMR_V1_FINGERPRINT,'b22433396fe82ec54461f449944cb780fedca7caa4f5fab4a440a0e980972f89');assert.equal(searchAblationSuiteFingerprint(PHASE3F_LMR_START_SUITE),config.fingerprint);
const key=(p:typeof PHASE3F_LMR_START_SUITE.starts[number]['position'])=>[p.side,p.p1Men>>>0,p.p1Kings>>>0,p.p2Men>>>0,p.p2Kings>>>0,p.halfmoveClock].join(':');
const prior=new Set([...SEARCH_ABLATION_START_SUITE.starts,...EXTENSION_CONFIRMATION_START_SUITE.starts,...PHASE3C_CONFIRMATION_START_SUITE.starts,...PHASE3C_FINAL_CONFIRMATION_START_SUITE.starts,...PHASE3D_CONFIRMATION_START_SUITE.starts,...PHASE3E_MOVE_ORDERING_START_SUITE.starts].map(s=>key(s.position)));
assert.equal(new Set(PHASE3F_LMR_START_SUITE.starts.map(s=>key(s.position))).size,64);assert(PHASE3F_LMR_START_SUITE.starts.every(s=>!prior.has(key(s.position))));assert.deepEqual(config.baselineSearch,DEFAULT_SEARCH_FEATURES);assert.deepEqual(config.baselineExtensions,DEFAULT_EXTENSION_FEATURES);assert.deepEqual(config.baselineMoveOrdering,DEFAULT_MOVE_ORDERING_FEATURES);
const signature=(r:SearchResult)=>({best:r.best,score:r.score,depth:r.depth,pv:r.pv,nodes:r.nodes,qnodes:r.qnodes});
async function main(){const p=PHASE3F_LMR_START_SUITE.starts[0].position,h=[hashPosition(p)];const a=await fixedNodeSearch(p,5000,new TT(),h);const b=await fixedNodeSearch(p,5000,new TT(),h,64,undefined,{}, {}, {},{lmrProfile:'current'});const c=await fixedNodeSearch(p,5000,new TT(),h,64,undefined,{}, {}, {},{lmrProfile:'current',collectLmrStats:true});assert.equal(a.lmrStats,undefined);assert.equal(b.lmrStats,undefined);assert(c.lmrStats);assert.deepEqual(signature(a),signature(b));assert.deepEqual(signature(a),signature(c));for(const profile of config.inventory){const [baseline,candidate]=makePhase3fEnginePair(profile,{mode:'nodes',budget:5000,maxDepth:64});assert.equal(baseline.measurementOptions?.lmrProfile,'current');assert.equal(candidate.measurementOptions?.lmrProfile,profile);assert.equal(candidate.measurementOptions?.collectLmrStats,true);}const [baseTime,candidateTime]=makePhase3fEnginePair('gentler',{mode:'time',budget:100,maxDepth:64});assert.equal(baseTime.measurementOptions?.collectLmrStats,undefined);assert.equal(candidateTime.measurementOptions?.collectLmrStats,undefined);
resetSearchHeuristicsForMeasurement();const directDefault=fixedDepthScoreAtPlyForTesting(p,4,0,new TT());const aggressive=await fixedNodeSearch(p,5000,new TT(),h,64,undefined,{}, {}, {},{lmrProfile:'aggressive',collectLmrStats:true});assert(aggressive.lmrStats);const statsSnapshot=structuredClone(aggressive.lmrStats);resetSearchHeuristicsForMeasurement();const directAfterMeasured=fixedDepthScoreAtPlyForTesting(p,4,0,new TT());assert.equal(directAfterMeasured,directDefault);assert.deepEqual(aggressive.lmrStats,statsSnapshot);console.log('PASS Phase 3F corpus, profiles, instrumentation, explicit-current identity, and direct-negamax isolation');}
main().catch(e=>{console.error(e);process.exitCode=1});
